# Actuator

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /delivery-actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: never
  individual:
    health:
